propel:
    database:
        connections:
            default:
                adapter: mysql
                dsn: mysql:host=localhost:3306;dbname=medium
                user: medium
                password: medium
                settings:
                    charset: utf8
